# Write your MySQL query statement below
WITH CTE AS
(SELECT 
D.NAME DEPARTMENT,E1.NAME  EMPLOYEE, SALARY  ,DENSE_RANK()  OVER ( PARTITION BY D.NAME  ORDER BY E1.SALARY DESC ) TOP FROM 
                EMPLOYEE E1 
                LEFT JOIN  DEPARTMENT D  ON E1.DEPARTMENTID = D.ID )

SELECT DEPARTMENT ,  EMPLOYEE ,SALARY
 FROM CTE  WHERE  TOP < 4 ; 